### PR TITLE
replace high voltage option with hardware_interface in launch menu ui

### PR DESCRIPTION
**Pull request by TimBuckers**
Now march.launch (exoskeleton) works correctly with (optional) hardware interface

### CODE REVIEW

**Comment by Ishadijcks** [comment]
You mention replacing but you only remove an option?

**Comment by TimBuckers** [comment]
Probably because there are conflicts

**Comment by Ishadijcks** [comment]
Can you fix them?

**Comment by TimBuckers** [comment]
I think I was fixing an problem that was already fixed

**Pull request closed without merging**
